set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 1 [current_design] 
set_property CONFIG_MODE SPIx1 [current_design] 
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
 set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR NO [current_design]

set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K4} [get_ports {i_clk_25m}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN N14} [get_ports {o_led[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P15} [get_ports {o_led[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P16} [get_ports {o_led[2]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN R16} [get_ports {o_led[3]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN U17} [get_ports {i_key[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P17} [get_ports {i_key[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V17} [get_ports {i_key[2]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN N17} [get_ports {i_key[3]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN U7} [get_ports {o_eth_led[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN U6} [get_ports {o_eth_led[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P5} [get_ports {o_eth_led[2]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN T6} [get_ports {o_eth_led[3]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J6} [get_ports {i_uart_rx}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J5} [get_ports {o_uart_tx}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN L6} [get_ports {sd_ncs}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN L5} [get_ports {sd_dclk}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN W6} [get_ports {sd_mosi}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V7} [get_ports {sd_miso}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P14} [get_ports {exter_io1[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN R14} [get_ports {exter_io1[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN Y18} [get_ports {exter_io1[2]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN W17} [get_ports {exter_io1[3]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN W19} [get_ports {exter_io1[4]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AA18} [get_ports {exter_io1[5]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN Y19} [get_ports {exter_io1[6]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AB18} [get_ports {exter_io1[7]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V18} [get_ports {exter_io1[8]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AA19} [get_ports {exter_io1[9]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AB20} [get_ports {exter_io1[10]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V19} [get_ports {exter_io1[11]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AA21} [get_ports {exter_io1[12]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AA20} [get_ports {exter_io1[13]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN Y21} [get_ports {exter_io1[14]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AB21} [get_ports {exter_io1[15]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN W20} [get_ports {exter_io1[16]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AB22} [get_ports {exter_io1[17]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN W21} [get_ports {exter_io1[18]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN Y22} [get_ports {exter_io1[19]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V20} [get_ports {exter_io1[20]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN W22} [get_ports {exter_io1[21]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN U21} [get_ports {exter_io1[22]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V22} [get_ports {exter_io1[23]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN T20} [get_ports {exter_io1[24]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN U20} [get_ports {exter_io1[25]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P20} [get_ports {exter_io1[26]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P19} [get_ports {exter_io1[27]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN L19} [get_ports {exter_io1[28]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN M18} [get_ports {exter_io1[29]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K16} [get_ports {exter_io1[30]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K19} [get_ports {exter_io1[31]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H19} [get_ports {exter_io1[32]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H18} [get_ports {exter_io1[33]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN R17} [get_ports {exter_io2[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN T18} [get_ports {exter_io2[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN R18} [get_ports {exter_io2[2]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN U18} [get_ports {exter_io2[3]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN R19} [get_ports {exter_io2[4]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN N18} [get_ports {exter_io2[5]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN N15} [get_ports {exter_io2[6]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN N19} [get_ports {exter_io2[7]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN M15} [get_ports {exter_io2[8]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN M16} [get_ports {exter_io2[9]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN L16} [get_ports {exter_io2[10]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN L15} [get_ports {exter_io2[11]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN N22} [get_ports {exter_io2[12]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K14} [get_ports {exter_io2[13]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J15} [get_ports {exter_io2[14]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J14} [get_ports {exter_io2[15]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H13} [get_ports {exter_io2[16]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J19} [get_ports {exter_io2[17]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H17} [get_ports {exter_io2[18]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H14} [get_ports {exter_io2[19]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G18} [get_ports {exter_io2[20]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H15} [get_ports {exter_io2[21]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G16} [get_ports {exter_io2[22]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G17} [get_ports {exter_io2[23]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F15} [get_ports {exter_io2[24]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F16} [get_ports {exter_io2[25]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E16} [get_ports {exter_io2[26]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E17} [get_ports {exter_io2[27]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN D15} [get_ports {exter_io2[28]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN D16} [get_ports {exter_io2[29]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN C17} [get_ports {exter_io2[30]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN C18} [get_ports {exter_io2[31]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN B17} [get_ports {exter_io2[32]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN B20} [get_ports {exter_io2[33]}]
set_property -dict {PACKAGE_PIN AB3 IOSTANDARD TMDS_33} [get_ports {o_hdmi_d_p[2]}]
set_property -dict {PACKAGE_PIN W2 IOSTANDARD TMDS_33} [get_ports {o_hdmi_d_p[1]}]
set_property -dict {PACKAGE_PIN AA1 IOSTANDARD TMDS_33} [get_ports {o_hdmi_d_p[0]}]
set_property -dict {PACKAGE_PIN W1 IOSTANDARD TMDS_33} [get_ports o_hdmi_clk_p]

# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN   } [get_ports {o_sdram_cke}] #恒3V3
# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN   } [get_ports {o_sdram_cs_n}] #恒GND
# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN   } [get_ports {o_sdram_dqm[0]}] #恒GND
# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN   } [get_ports {o_sdram_dqm[1]}] #恒GND
# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN   } [get_ports {o_sdram_dqm[2]}] #恒GND
# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN   } [get_ports {o_sdram_dqm[3]}] #恒GND
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  E14 } [get_ports {o_sdram_clk}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  D17 } [get_ports {o_sdram_we_n}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  D14 } [get_ports {o_sdram_cas_n}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  A14 } [get_ports {o_sdram_ras_n}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  D19 } [get_ports {o_sdram_ba[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  B13 } [get_ports {o_sdram_ba[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  C20 } [get_ports {o_sdram_addr[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  C19 } [get_ports {o_sdram_addr[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  C13 } [get_ports {o_sdram_addr[2]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  F13 } [get_ports {o_sdram_addr[3]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  G13 } [get_ports {o_sdram_addr[4]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  G15 } [get_ports {o_sdram_addr[5]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  F14 } [get_ports {o_sdram_addr[6]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  F18 } [get_ports {o_sdram_addr[7]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  E13 } [get_ports {o_sdram_addr[8]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  E18 } [get_ports {o_sdram_addr[9]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  C14 } [get_ports {o_sdram_addr[10]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  F21 } [get_ports {io_sdram_dq[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  E22 } [get_ports {io_sdram_dq[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  F20 } [get_ports {io_sdram_dq[2]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  E21 } [get_ports {io_sdram_dq[3]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  F19 } [get_ports {io_sdram_dq[4]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  D22 } [get_ports {io_sdram_dq[5]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  E19 } [get_ports {io_sdram_dq[6]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  D21 } [get_ports {io_sdram_dq[7]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  K21 } [get_ports {io_sdram_dq[8]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  L21 } [get_ports {io_sdram_dq[9]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  K22 } [get_ports {io_sdram_dq[10]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  M21 } [get_ports {io_sdram_dq[11]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  L20 } [get_ports {io_sdram_dq[12]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  M22 } [get_ports {io_sdram_dq[13]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  N20 } [get_ports {io_sdram_dq[14]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  M20 } [get_ports {io_sdram_dq[15]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  B18 } [get_ports {io_sdram_dq[16]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  D20 } [get_ports {io_sdram_dq[17]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  A19 } [get_ports {io_sdram_dq[18]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  A21 } [get_ports {io_sdram_dq[19]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  A20 } [get_ports {io_sdram_dq[20]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  B21 } [get_ports {io_sdram_dq[21]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  C22 } [get_ports {io_sdram_dq[22]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  B22 } [get_ports {io_sdram_dq[23]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  G21 } [get_ports {io_sdram_dq[24]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  G22 } [get_ports {io_sdram_dq[25]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  H20 } [get_ports {io_sdram_dq[26]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  H22 } [get_ports {io_sdram_dq[27]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  J20 } [get_ports {io_sdram_dq[28]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  J22 } [get_ports {io_sdram_dq[29]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  G20 } [get_ports {io_sdram_dq[30]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  J21 } [get_ports {io_sdram_dq[31]}]